server:
  port: 80

spring:
  redis:
#    database: 0 # Redis数据库索引（默认为0）
    host: 47.52.232.245
#    port: 6379
    password: quechao007
    timeout: 1000   # 连接超时时间（毫秒）
    jedis:
      pool:
        max-wait: 1000ms  #最大等待时间
        min-idle: 1 #最小空闲连接数数量
        max-idle: 10  #最大空闲连接数数量
        max-active: 50  #最大连接数量
